defaults:
  - _self_
  - data: amplify_entropy.yaml
  - model: entropy_2M.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - setup: default.yaml
  - paths: default.yaml
  - plugins: null
  - experiment: null

dryrun: false
run_test: null
compile: false